"""Add logo fields to certificate templates

Revision ID: 004_certificate_template_logo
Revises: 003_certificate_templates
Create Date: 2025-01-14 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '004_certificate_template_logo'
down_revision = '003_certificate_templates'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_templates', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('certificate_templates', sa.Column('logo_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate_templates', 'logo_public_id')
    op.drop_column('certificate_templates', 'logo_url')
    # ### end Alembic commands ###