"""Add event certificates tables

Revision ID: 005_event_certificates
Revises: 004_certificate_template_logo
Create Date: 2025-01-14 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '005_event_certificates'
down_revision = '004_certificate_template_logo'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('certificate_template_id', sa.Integer(), nullable=False),
    sa.Column('template_variables', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_template_id'], ['certificate_templates.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_certificates_event_id'), 'event_certificates', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_certificates_id'), 'event_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_event_certificates_tenant_id'), 'event_certificates', ['tenant_id'], unique=False)
    
    op.create_table('participant_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_certificate_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('certificate_public_id', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_certificate_id'], ['event_certificates.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['event_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_certificates_event_certificate_id'), 'participant_certificates', ['event_certificate_id'], unique=False)
    op.create_index(op.f('ix_participant_certificates_id'), 'participant_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_participant_certificates_participant_id'), 'participant_certificates', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participant_certificates_participant_id'), table_name='participant_certificates')
    op.drop_index(op.f('ix_participant_certificates_id'), table_name='participant_certificates')
    op.drop_index(op.f('ix_participant_certificates_event_certificate_id'), table_name='participant_certificates')
    op.drop_table('participant_certificates')
    op.drop_index(op.f('ix_event_certificates_tenant_id'), table_name='event_certificates')
    op.drop_index(op.f('ix_event_certificates_id'), table_name='event_certificates')
    op.drop_index(op.f('ix_event_certificates_event_id'), table_name='event_certificates')
    op.drop_table('event_certificates')
    # ### end Alembic commands ###