"""Add badge templates table

Revision ID: 009_badge_templates
Revises: 024_invitation_templates
Create Date: 2024-12-23 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '009_badge_templates'
down_revision = '024_invitation_templates'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_content', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('logo_public_id', sa.String(length=255), nullable=True),
    sa.Column('background_url', sa.String(length=500), nullable=True),
    sa.Column('background_public_id', sa.String(length=255), nullable=True),
    sa.Column('enable_qr_code', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('badge_size', sa.String(length=50), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badge_templates_id'), 'badge_templates', ['id'], unique=False)
    op.create_index(op.f('ix_badge_templates_name'), 'badge_templates', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_badge_templates_name'), table_name='badge_templates')
    op.drop_index(op.f('ix_badge_templates_id'), table_name='badge_templates')
    op.drop_table('badge_templates')
    # ### end Alembic commands ###