"""add_invitation_templates_table

Revision ID: 024_invitation_templates
Revises: 023_cert_templates
Create Date: 2025-01-04 16:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '024_invitation_templates'
down_revision = '023_cert_templates'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('logo_public_id', sa.String(length=255), nullable=True),
    sa.Column('watermark_url', sa.String(length=500), nullable=True),
    sa.Column('watermark_public_id', sa.String(length=255), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('signature_public_id', sa.String(length=255), nullable=True),
    sa.Column('enable_qr_code', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('address_fields', sa.JSON(), nullable=True),
    sa.Column('signature_footer_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_templates_id'), 'invitation_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_templates_id'), table_name='invitation_templates')
    op.drop_table('invitation_templates')
    # ### end Alembic commands ###