"""Add feedback_prompts table

Revision ID: 092_add_feedback_prompts_table
Revises: 091_add_accommodation_deduction_fields
Create Date: 2024-02-02 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092_add_feedback_prompts_table'
down_revision = '091_add_accommodation_deduction'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_prompts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_prompted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_count', sa.Integer(), nullable=True),
    sa.Column('dismissed_count', sa.Integer(), nullable=True),
    sa.Column('has_submitted_feedback', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_prompts_id'), 'feedback_prompts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_prompts_id'), table_name='feedback_prompts')
    op.drop_table('feedback_prompts')
    # ### end Alembic commands ###