"""Add app_feedback table

Revision ID: 093_add_app_feedback_table
Revises: 092_add_feedback_prompts_table
Create Date: 2024-02-02 12:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093_add_app_feedback_table'
down_revision = '092_add_feedback_prompts_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    op.execute("CREATE TYPE feedbackcategory AS ENUM ('user_experience', 'performance', 'features', 'bug_report', 'suggestion', 'general')")
    
    op.create_table('app_feedback',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('user_experience', 'performance', 'features', 'bug_report', 'suggestion', 'general', name='feedbackcategory'), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_feedback_id'), 'app_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_feedback_id'), table_name='app_feedback')
    op.drop_table('app_feedback')
    op.execute('DROP TYPE IF EXISTS feedbackcategory')
    # ### end Alembic commands ###