"""Add travel checklist progress table

Revision ID: travel_checklist_001
Revises: 
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'travel_checklist_001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_checklist_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('checklist_items', sa.JSON(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_checklist_progress_event_id'), 'travel_checklist_progress', ['event_id'], unique=False)
    op.create_index(op.f('ix_travel_checklist_progress_id'), 'travel_checklist_progress', ['id'], unique=False)
    op.create_index(op.f('ix_travel_checklist_progress_user_email'), 'travel_checklist_progress', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_checklist_progress_user_email'), table_name='travel_checklist_progress')
    op.drop_index(op.f('ix_travel_checklist_progress_id'), table_name='travel_checklist_progress')
    op.drop_index(op.f('ix_travel_checklist_progress_event_id'), table_name='travel_checklist_progress')
    op.drop_table('travel_checklist_progress')
    # ### end Alembic commands ###