"""Add passport_records table

Revision ID: passport_records_001
Revises: f1895cdab0c6
Create Date: 2024-10-31 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'passport_records_001'
down_revision = 'f1895cdab0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passport_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_index(op.f('ix_passport_records_id'), 'passport_records', ['id'], unique=False)
    op.create_index(op.f('ix_passport_records_user_email'), 'passport_records', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passport_records_user_email'), table_name='passport_records')
    op.drop_index(op.f('ix_passport_records_id'), table_name='passport_records')
    op.drop_table('passport_records')
    # ### end Alembic commands ###