"""Add notifications table with enhanced features

Revision ID: aff03164daa5
Revises: 45a9fb45589b
Create Date: 2025-08-05 00:32:43.718149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff03164daa5'
down_revision = '45a9fb45589b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###